### ISSUE TITLE
Icon blurred

### ISSUE THREAD

**Issue by quozl** [sugarlabs/flappy#14]
https://v4.activities.sugarlabs.org/app/org.ceibaljam.flappy.html icon for activity is blurred.

It looks like the activity icon is _not scalable_.  We need a new icon designed please.  @perriefidelis?

**Comment by middletonmc** [comment]
Does the redesign need to stay in the .xo file type or can they be something else?

**Comment by chimosky** [comment]
Our icons are usually designed in svg, the current [activity icon](https://github.com/sugarlabs/flappy/blob/master/activity/flappy.svg) is also in svg. 

.xo files are created with the `./setup.py dist_xo` command, which bundles the activity to a .xo file that can be run in sugar.

You can read more about our [icons](https://wiki.sugarlabs.org/go/Human_Interface_Guidelines/The_Sugar_Interface/Icons).
