### ISSUE TITLE
Game speed feature

### ISSUE THREAD

**Issue by quozl** [sugarlabs/flappy#5]
It is difficult to test the activity because it requires developing skill, and once the skill is developed it is no longer possible to test the activity as a neophyte.

Add a three-speed feature; as three radio buttons in tool bar, 33% and 50% of standard speed, and use Sugar icons for age; baby for 33%, adult for standard.  Default to the standard speed.

**Comment by rhl-bthr** [comment]
Fixed in d4d4c7d
